kamel:
  run:
    integration:
      crime-bridge:
        property-files: '[application.properties]'
        dependencies: '[mvn:org.apache.activemq:artemis-jms-client:2.11.0.redhat-00005,mvn:com.github.openshift-integration:camel-k-example-event-streaming:master-SNAPSHOT]'
      earthquake-bridge:
        property-files: '[application.properties]'
        dependencies: '[mvn:org.apache.activemq:artemis-jms-client:2.11.0.redhat-00005,mvn:com.github.openshift-integration:camel-k-example-event-streaming:master-SNAPSHOT]'
      earthquake-consumer:
        property-files: '[application.properties]'
        dependencies: '[mvn:com.github.openshift-integration:camel-k-example-event-streaming:master-SNAPSHOT]'
      health-bridge:
        property-files: '[application.properties]'
        dependencies: '[mvn:org.apache.activemq:artemis-jms-client:2.11.0.redhat-00005,mvn:com.github.openshift-integration:camel-k-example-event-streaming:master-SNAPSHOT]'
      open-aq-consumer:
        property-files: '[application.properties]'
        dependencies: '[mvn:com.github.openshift-integration:camel-k-example-event-streaming:master-SNAPSHOT]'
      pollution-bridge:
        property-files: '[application.properties]'
        dependencies: '[mvn:org.apache.qpid:qpid-jms-client:0.45.0.redhat-00002,mvn:com.github.openshift-integration:camel-k-example-event-streaming:master-SNAPSHOT]'
      timeline-bridge:
        property-files: '[application.properties]'
        dependencies: '[camel-jackson,mvn:com.github.openshift-integration:camel-k-example-event-streaming:master-SNAPSHOT]'
      user-report-system:
        dependencies: '[mvn:com.github.openshift-integration:camel-k-example-event-streaming:master-SNAPSHOT]'
        secrets: '[example-event-streaming-user-reporting]'
